### ISSUE TITLE
Tagging Not Working 

### ISSUE THREAD

**Issue by jordan-simonovski** [ButlerLogic/action-autotag#2]
It seems as though the package.json's version is being picked up, but a tag is not being pushed.
I've attached a screenshot of what this looks like in actions.
<img width="412" alt="image" src="https://user-images.githubusercontent.com/11486222/64610044-b522cc80-d411-11e9-9a27-ee417195e285.png">

**Comment by coreybutler** [comment]
This means it's failing after [line 27](https://github.com/ButlerLogic/action-autotag/blob/master/lib/main.js#L27)

My best guess is one of the calls to the Github API is failing. If there is no response, it shouldn't throw an error, but I strongly suspect that's what octokit (the API client) is doing.

@jordan-simonovski - do you have any existing tags yet? I should probably add a handler (or at least a better error message), but knowing that would help me track down the cause.

**Comment by coreybutler** [comment]
I've proactively added better error handling to that particular segment. You can test it using master.

**Comment by miljantekic** [comment]
@coreybutler Thanks for getting back so quickly. Unfortunately, I somehow missed the notification.

I'm getting the following error now:

![image](https://user-images.githubusercontent.com/6766291/65154870-8f5a8080-da2c-11e9-838b-1012d0306d44.png)

**Comment by coreybutler** [comment]
@miljantekic - Did you have any prior commits/tags?

I'm fairly sure this error was thrown because the Github API failed to return a changelog (which is used for the tag message). If you didn't have a prior tag/commit, it wouldn't find a diff. That's a legit use case, so instead of aborting, I've defaulted the tag message to the tag name. It will bail if the tag cannot be created for any other reason though.

This is updated in master. Let me know if it works for you, and apologies for all the issues!

**Comment by miljantekic** [comment]
Unfortunately nope :( Still same issue

![image](https://user-images.githubusercontent.com/6766291/65251979-7e774100-daf8-11e9-9cf9-305adfde46be.png)

I have two prior tags, and there is always a commit that triggers the version bump in package.json. Is that enough?

The github repo is public so you can check if helps you in any way.
https://github.com/Tenderly/tenderly-dashboard/commits/master

No worries, it's not causing any trouble as I'm still validating GitHub actions so it's not used for anything crucial. Happy to be of any help to fix issues :)

**Comment by coreybutler** [comment]
@miljantekic I forked the repo and couldn't recreate the error.

![image](https://user-images.githubusercontent.com/770982/65267319-609ae380-dada-11e9-856e-883ae32227da.png)

![image](https://user-images.githubusercontent.com/770982/65267651-10705100-dadb-11e9-9e92-ea0190f7e991.png)


That said, I _did have to modify the workflow file_ in order for the action to run at all. The first few commits didn't trigger anything. It makes me wonder if there is some sort of caching happening.

Anyhow, it's possible to see more verbose output by setting `ACTIONS_STEP_DEBUG: true`.

![image](https://user-images.githubusercontent.com/770982/65267503-bcfe0300-dada-11e9-8498-039a8bdf9d0c.png)

I'm curious if merely changing the name of the workflow file could potentially flush a cache, or if there is something else going on.

**Comment by miljantekic** [comment]
@coreybutler Interesting find, and thanks for putting in the effort :D

I've forked the repo on my personal account also and got it to work. (tho I did notice that the tag was not prefixed with "v", same in your screenshot also). 

So it seems that's it definitely a bug on the GitHub Actions part. 

But unfortunately I'm still unable to get it working on the main repo, I've tried changing the name, adding the debug flag and everything. Tho one interesting thing is when I changed the `runs-on` machine the error also changed. 

![image](https://user-images.githubusercontent.com/6766291/65312704-60125380-db93-11e9-8da9-0bccaa50d438.png)

I think that's that for this issue (eventually the prefix issue now :P). Thanks again and cheers!

**Comment by sampsonjoliver** [comment]
Just thought I'd chime in, I also just added this integration, and am getting

```
Run butlerlogic/action-autotag@stable
##[set-output name=version;]2.6.0
##[error]Not Found
##[error]Node run failed with exit code 1
```

when running on my workplace's repo, even with `ACTIONS_STEP_DEBUG: true`.

**Comment by coreybutler** [comment]
Apologies for the huge delay... got wrapped up in other projects. I've merged @oomathias PR, which does appear to resolve the issue. If the issue remains, let me know and I'll reopen it.
