### ISSUE TITLE
Make this githubaction using node12 instead of docker

### ISSUE THREAD

**Issue by RolfJordi** [ButlerLogic/action-autotag#20]
this is a feature request. 

this githubaction won't run on windows or macos vm. But all the code is in js. 

Is it possible to transform the action to a node12 action?

**Comment by coreybutler** [comment]
In a "better late than never", this action now uses `node16`.

This action required features of Node 13+ (which Github didn't support at the time of the original issue submission), thus why it was originally based on Docker. Now that Node 16 is supported, Docker is no longer necessary.
